/glg4debug/glg4param omit_muon_processes  1.0
/glg4debug/glg4param omit_hadronic_processes  1.0

/tracking/verbose 0

/tracking/storeTrajectory 1
/tracking/discardParticleTrajectory opticalphoton

/rat/db/set DETECTOR experiment "ANNIE"
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config3.geo"

/run/initialize

/process/activate Cerenkov
/glg4scint/on
#/glg4scint/reemission on

/process/inactivate DeferTrackProc all
/process/activate DeferTrackProc gamma
/process/activate DeferTrackProc e+
/process/activate DeferTrackProc e-

#initialize the visualizer
/vis/open OGLIQt 2000
/vis/scene/create

/vis/scene/add/volume
/vis/scene/add/trajectories
/vis/viewer/reset
/vis/viewer/set/style surface
#/vis/viewer/set/upVector 1 0 0
/vis/drawVolume

#/vis/viewer/set/viewpointThetaPhi 20 20
/vis/viewer/set/viewpointVector 1.0 1.0 -0.2
/vis/viewer/zoom 1.4
/vis/viewer/pan -500 -2000 1000 mm
/vis/viewer/set/upVector 0 0 1

#####################
# BEGIN EVENT LOOP

/rat/proc simpledaq
/rat/proc count
/rat/procset update 10
/rat/proc fitcentroid
/rat/proc prune
/rat/procset prune "mc.track:opticalphoton"

# Use IO.default_output_filename
/rat/proclast outroot

/generator/add combo gun:point
/generator/vtx/set geantino -1 0 0 10
/generator/pos/set 793.7 0.0 1470.0
#/generator/vtx/set neutron 0 0 0 1
#/generator/pos/set 1000 0 1377.2
#/generator/pos/set 100 100 0
#/generator/pos/set NCVliquid

/run/beamOn 1000

#END EVENT LOOP
#####################

/vis/viewer/refresh
/vis/viewer/flush



